# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/iuni/nbl8910a/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/iuni/nbl8910a/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/iuni/nbl8910a/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/iuni/nbl8910a/proprietary/lib/hw/camera.vendor.nbl8910a.so:system/lib/hw/camera.vendor.nbl8910a.so \
    vendor/iuni/nbl8910a/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/iuni/nbl8910a/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/iuni/nbl8910a/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/iuni/nbl8910a/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libAKM8963.so:system/vendor/lib/libAKM8963.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_hfr_120.so:system/vendor/lib/libchromatix_imx214_hfr_120.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_hfr_60.so:system/vendor/lib/libchromatix_imx214_hfr_60.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_liveshot.so:system/vendor/lib/libchromatix_imx214_liveshot.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_preview_binning.so:system/vendor/lib/libchromatix_imx214_preview_binning.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib/libchromatix_imx214_snapshot_hdr.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_video_binning.so:system/vendor/lib/libchromatix_imx214_video_binning.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_video_cmcc.so:system/vendor/lib/libchromatix_imx214_video_cmcc.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_imx214_video_hdr.so:system/vendor/lib/libchromatix_imx214_video_hdr.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_default_video.so:system/vendor/lib/libchromatix_ov5648_default_video.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_preview.so:system/vendor/lib/libchromatix_ov5648_preview.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_preview_fb.so:system/vendor/lib/libchromatix_ov5648_preview_fb.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_video_cmcc.so:system/vendor/lib/libchromatix_ov5648_video_cmcc.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_zsl.so:system/vendor/lib/libchromatix_ov5648_zsl.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libchromatix_ov5648_zsl_fb.so:system/vendor/lib/libchromatix_ov5648_zsl_fb.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_ov5648.so:system/vendor/lib/libmmcamera_ov5648.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_sony_imx214_eeprom.so:system/vendor/lib/libmmcamera_sony_imx214_eeprom.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/iuni/nbl8910a/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/iuni/nbl8910a/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/iuni/nbl8910a/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/iuni/nbl8910a/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/iuni/nbl8910a/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/iuni/nbl8910a/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/iuni/nbl8910a/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/iuni/nbl8910a/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/iuni/nbl8910a/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/iuni/nbl8910a/proprietary/bin/radish:system/bin/radish \
    vendor/iuni/nbl8910a/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/iuni/nbl8910a/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/iuni/nbl8910a/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/iuni/nbl8910a/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/iuni/nbl8910a/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/iuni/nbl8910a/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/iuni/nbl8910a/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/iuni/nbl8910a/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/iuni/nbl8910a/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/iuni/nbl8910a/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/iuni/nbl8910a/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/iuni/nbl8910a/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/iuni/nbl8910a/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/iuni/nbl8910a/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/iuni/nbl8910a/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/iuni/nbl8910a/proprietary/lib/libwcnss_qmi.so:system/lib/libwcnss_qmi.so \
    vendor/iuni/nbl8910a/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/hw/activity_recognition.msm8974.so:system/vendor/lib/hw/activity_recognition.msm8974.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/hw/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/iuni/nbl8910a/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    libmdmdetect \
    libwpa_qmi_eap_proxy \
    libTimeService \
    libdiag \
    libdsutils \
    libidl \
    liblisten \
    libqcci_legacy \
    libqmi \
    libqmi_client_qmux \
    libqmiservices \
    libtime_genoff \
    TimeService \
    shutdownlistener \
    qcrilmsgtunnel
endif
